# Manual zshrc start

if [ -f "$HOME/.local/bin/env" ]; then
    . "$HOME/.local/bin/env"
fi

# if runs on darwin, add some paths to PATH
if [[ "$OSTYPE" == "darwin"* ]]; then
    export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"
    export PATH="/Applications/MacVim.app/Contents/bin:$PATH"
    export SSH_AUTH_SOCK=/Users/toku163/.bitwarden-ssh-agent.sock
fi

function _fzf_cd_ghq() {
    FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --reverse --height=50%"
    local root="$(ghq root)"
    local repo="$(ghq list | fzf --preview="ls -AF --color=always ${root}/{1}")"
    local dir="${root}/${repo}"
    [ -n "${dir}" ] && cd "${dir}"
    zle accept-line
    zle reset-prompt
}

zle -N _fzf_cd_ghq
bindkey "^g" _fzf_cd_ghq

export HOMEBREW_NO_ENV_HINTS=1

eval "$(uv generate-shell-completion zsh)"

export PATH="$PATH:$HOME/go/bin/"

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Manual zshrc end
